- name: "Add docker apt key"
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- name: "Install docker apt repository"
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present

- name: "Update repositories cache"
  apt:
    force_apt_get: yes
    update_cache: yes

- name: "Upgrade packages to the latest version"
  apt:
    force_apt_get: yes
    upgrade: dist

- name: "Install required packages"
  apt:
    name: "{{ packages }}"
    force_apt_get: yes
    state: latest
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - python
      - python3
      - python-apt
      - python3-apt
      - python-pip
      - python3-pip
      - docker-ce

- name: "Install required packages (Ubuntu only)"
  apt:
    name: "{{ packages }}"
    force_apt_get: yes
    state: latest
  vars:
    packages:
      - linux-aws
  when: ansible_distribution == 'Ubuntu'

- name: "Add user to docker group"
  user:
    name: "{{ ansible_ssh_user }}"
    groups: docker
    append: yes

- name: "Enable docker service, and start it"
  systemd:
    name: docker
    enabled: yes
    masked: no
    state: started

- name: "Install pip2 packages"
  pip:
    name: "{{ pippkgs }}"
    executable: pip2
    state: latest
  vars:
    pippkgs:
      - pip
      - docker
      - docker-compose
      - PyYAML

- name: "Install pip3 packages"
  pip:
    name: "{{ pippkgs }}"
    executable: pip3
    state: latest
  vars:
    pippkgs:
      - pip
      - docker
      - docker-compose
      - PyYAML

- name: "Create hard core limit file"
  file:
    path: /etc/security/limits.d/10.hardcore.conf
    mode: '0644'
    state: touch
    owner: root
    group: root

- name: "Copy over the docker-compose file"
  copy:
    src: ../data/docker-compose.yaml
    dest: /home/{{ ansible_ssh_user }}/docker-compose.yaml
    mode: '0440'
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"

- name: "Copy over the nginx conf files"
  synchronize:
    src: ../data/nginx
    dest: /home/{{ ansible_ssh_user }}/
    mode: '0440'
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
